### ISSUE TITLE
Padding? increases after each batch between paragraph input and table

### ISSUE THREAD

**Issue by kortemik** [teragrep/ajs_01#177]
ID <282>
Reporter <@eemhu>

Seems like the padding? ( or maybe it's trying to draw the other type of table when aggregates are not used with empty data, just a guess) is increasing after each processed batch.

You can resize it and it disappears if you do that.

[![padding.webm](/com-teragrep/ajs_01/issue/raw/files/3c7c525d5b4c954522e23ad939119498c3c54266fc0c2eef01b0adb4edb1d0d7-padding.webm)](/com-teragrep/ajs_01/issue/raw/files/3c7c525d5b4c954522e23ad939119498c3c54266fc0c2eef01b0adb4edb1d0d7-padding.webm)

**Comment by ronja-ui** [comment]
since the height resizing feature was removed, this doesn't occur in this scale anymore. 

however, there is still the empty paragraph div for text content. at maximum its height is ~16px which isn't that much but it makes the whole paragraph-output to fidget. 

the correct solution to this problem is to ensure there's no empty div containers in paragraph-output.

**Comment by BVVLD** [comment]
the server sometimes starts to send this message on every batch update:
{
  "op": "PARAGRAPH_APPEND_OUTPUT",
  "data": {
    "data": "\n",
    "index": 0,
    "noteId": "2JEF7JF7C",
    "paragraphId": "paragraph_1699456285230_571125281"
  },
  "ticket": "anonymous",
  "principal": "anonymous",
  "roles": ""
}

Which adds a /n to the text output on every batch, resulting it growing in size

**Comment by BVVLD** [comment]
The problem is currently partially solved from UI side by watching for such updates and ignoring them. This is not a right way to solve it in long term, but a temporal measure to prevent UI breaking and slowing down, due to the piling up paragraph updates.
