### ISSUE TITLE
Error message doesn't disappear in note-create

### ISSUE THREAD

**Issue by ronja-ui** [teragrep/ajs_01#194]
"Input is not valid. Please, use only letters, numbers and symbols "/" "-" and "_"." error message doesn't disappear even if you enter a correct name for a notebook in note-create.

**Comment by BVVLD** [comment]
The issue was most likely caused by the validation code and logic for checking Enter key pressed being  combined and triggered by non-optimal event listener. The logic was refactored and separated. 
The issue also now is provided with test suite, which ensures that validation logic is working correctly, all scope variables, responsible for showing error messages, are changed in the right time and note-create function is called only in the right situation.
